### ISSUE TITLE
Problems to run cyTOFcompensation

### ISSUE THREAD

**Issue by algebio** [BodenmillerGroup/cyTOFcompensation#5]
Hello 

I am trying to check the compensation of my imc files. I have tried to run the conda env and the docker file on my Windows 10 laptop but due to my lack of experience with coda and docker, I haven't been able to run it. I would appreciate some help.

This is the error I get with conda after downloading environment.yml on C:\

(base) C:\>conda env create -f environment.yml -n cytofcompensation
Solving environment: failed

ResolvePackageNotFound:
  - bioconductor-flowcore
  - bioconductor-catalyst=1.6
  - bioconductor-biobase[version='>=2.42.0,<2.43.0']
  - bioconductor-catalyst=1.6
  - bioconductor-consensusclusterplus[version='>=1.46.0,<1.47.0']
  - bioconductor-all[version='>=1.24.0,<1.25.0']
  - wget
  - bioconductor-catalyst=1.6
  - bioconductor-flowcore[version='>=1.48.0,<1.49.0']
  - bioconductor-catalyst=1.6
  - bioconductor-flowsom[version='>=1.14.0,<1.15.0']
  - bioconductor-catalyst=1.6
  - bioconductor-limma[version='>=3.38.0,<3.39.0']
  - bioconductor-catalyst=1.6
  - bioconductor-s4vectors[version='>=0.20.0,<0.21.0']
  - bioconductor-catalyst=1.6
  - bioconductor-summarizedexperiment[version='>=1.12.0,<1.13.0']
  - bioconductor-delayedarray[version='>=0.8.0,<0.9.0']
  - bioconductor-catalyst=1.6
  - bioconductor-summarizedexperiment[version='>=1.12.0,<1.13.0']
  - bioconductor-genomeinfodb[version='>=1.18.0,<1.19.0']
  - bioconductor-iranges[version='>=2.16.0,<2.17.0']
  - bioconductor-catalyst=1.6
  - bioconductor-summarizedexperiment[version='>=1.12.0,<1.13.0']
  - bioconductor-genomicranges[version='>=1.34.0,<1.35.0']
  - bioconductor-ebimage
  - libgfortran

(base) C:\>

This is the error I get with Docker after downloading Dockerfiler.cytofcompensation:

 H:\>docker run cytofcompensation
Unable to find image 'cytofcompensation:latest' locally
docker: Error response from daemon: pull access denied for cytofcompensation, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

H:\>docker run Dockerfile.cytofcompensation
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.

I installed Anaconda and Docker today, so I assume I'm using the latest version available. 

As I said, I would appreciate some instructions (for dummies) on how to run the scripts for compensation of imc files.

Regards
Juan

**Comment by algebio** [comment]
An update:

I installed Ubuntu using WSL, then I installed miniconda and (after several days trying) the conda environment. I can activate it (conda activate cytofcompensation) but after the command rstudio, I get this:(base) njo47@FMS-IGM-19L005:~$ conda activate cytofcompensation
(cytofcompensation) njo47@FMS-IGM-19L005:~$ rstudio
QFactoryLoader::QFactoryLoader() checking directory path "/home/njo47/miniconda3/envs/cytofcompensation/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/home/njo47/miniconda3/envs/cytofcompensation/plugins/platforms/libqeglfs.so"
Found metadata in lib /home/njo47/miniconda3/envs/cytofcompensation/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 329219
}


Got keys from plugin meta data ("eglfs")
QFactoryLoader::QFactoryLoader() looking at "/home/njo47/miniconda3/envs/cytofcompensation/plugins/platforms/libqminimal.so"
Found metadata in lib /home/njo47/miniconda3/envs/cytofcompensation/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 329219
}


Got keys from plugin meta data ("minimal")
QFactoryLoader::QFactoryLoader() looking at "/home/njo47/miniconda3/envs/cytofcompensation/plugins/platforms/libqminimalegl.so"
Found metadata in lib /home/njo47/miniconda3/envs/cytofcompensation/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 329219
}


Got keys from plugin meta data ("minimalegl")
QFactoryLoader::QFactoryLoader() looking at "/home/njo47/miniconda3/envs/cytofcompensation/plugins/platforms/libqoffscreen.so"
Found metadata in lib /home/njo47/miniconda3/envs/cytofcompensation/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 329219
}


Got keys from plugin meta data ("offscreen")
QFactoryLoader::QFactoryLoader() looking at "/home/njo47/miniconda3/envs/cytofcompensation/plugins/platforms/libqxcb.so"
Found metadata in lib /home/njo47/miniconda3/envs/cytofcompensation/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 329219
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/njo47/miniconda3/envs/cytofcompensation/bin/platforms" ...
loaded library "/home/njo47/miniconda3/envs/cytofcompensation/plugins/platforms/libqxcb.so"
QLibraryPrivate::loadPlugin failed on "/home/njo47/miniconda3/envs/cytofcompensation/plugins/platforms/libqxcb.so" : "Cannot load library /home/njo47/miniconda3/envs/cytofcompensation/plugins/platforms/libqxcb.so: (libEGL.so.1: cannot open shared object file: No such file or directory)"
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
(cytofcompensation) njo47@FMS-IGM-19L005:~$


I check for the package libqxcb for Ubuntu bionic but I couldn't find it. 

What can I do? Any idea?

Regards
Juan

**Comment by votti** [comment]
Hi Juan,

I am extremly sorry for not getting back to you earlier - I am having a new job and the last weeks have been extremely busy.
 
I think nowadays you could just use imcRtools in conjunction with a recent version of CATALYST.
Please find here our work-in-progress ImcDataAnalysis guide: https://bodenmillergroup.github.io/IMCDataAnalysis/spillover-correction.html

Sorry again for causing you to spend unnecessary time on getting the old code running :(

Could you give feedback if this works for you as well?

Best and sorry again!
Vito

**Comment by votti** [comment]
I think this link is more up-to-date: https://bioconductor.org/packages/devel/bioc/vignettes/imcRtools/inst/doc/imcRtools.html#4_Spillover_correction

**Comment by algebio** [comment]
Hi Vito

Thank you for pointing me in the right direction. I'll give you feedback asap.

Congratulations on your new job and thanks again for helping us.

Regards
Juan

**Comment by algebio** [comment]
Hi Vito

imcRtools works well.

Thanks again to you, to Nils and everyone else involve in this project for sharing these excellent tools for free.

Regards
Juan
